### ISSUE TITLE
error C4582, failed to build RiderLink plugin

### ISSUE THREAD

**Issue by oktomus** [JetBrains/UnrealLink#186]
I'm trying to install RiderLink on UE 4.26 but building fails: 

```cpp
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1247): error C4582: 'fmt::v8::detail::value<Context>::no_value': constructor is not implicitly called
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1247): note: while compiling class template member function 'fmt::v8::detail::value<Context>::value(fmt::v8::basic_string_view<char>)'
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1731): note: see reference to function template instantiation 'fmt::v8::detail::value<Context>::value(fmt::v8::basic_string_view<char>)' being compiled
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1079): note: see reference to class template instantiation 'fmt::v8::detail::value<Context>' being compiled
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1835): note: see reference to class template instantiation 'fmt::v8::detail::arg_data<fmt::v8::detail::value<Context>,char,0,0>' being compiled
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/format.h(2473): note: see reference to class template instantiation 'fmt::v8::format_arg_store<fmt::v8::format_context>' being compiled
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/xchar.h(211): note: see reference to function template instantiation 'std::system_error fmt::v8::system_error<>(int,fmt::v8::basic_format_string<char>)' being compiled
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1243): error C4582: 'fmt::v8::detail::value<Context>::no_value': constructor is not implicitly called
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1243): note: while compiling class template member function 'fmt::v8::detail::value<Context>::value(const char *)'
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1731): note: see reference to function template instantiation 'fmt::v8::detail::value<Context>::value(const char *)' being compiled
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1232): error C4582: 'fmt::v8::detail::value<Context>::no_value': constructor is not implicitly called
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1232): note: while compiling class template member function 'fmt::v8::detail::value<Context>::value(int)'
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1731): note: see reference to function template instantiation 'fmt::v8::detail::value<Context>::value(int)' being compiled
            with
            [
                Context=fmt::v8::format_context
            ]
    [68/79] Module.RiderLink.cpp
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/chrono.h(1558): error C4582: 'fmt::v8::detail::get_locale::locale_': constructor is not implicitly called
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/chrono.h(1562): error C4583: 'fmt::v8::detail::get_locale::locale_': destructor is not implicitly called
    [69/79] Module.RiderBlueprint.cpp
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1247): error C4582: 'fmt::v8::detail::value<Context>::no_value': constructor is not implicitly called
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1247): note: while compiling class template member function 'fmt::v8::detail::value<Context>::value(fmt::v8::basic_string_view<char>)'
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1731): note: see reference to function template instantiation 'fmt::v8::detail::value<Context>::value(fmt::v8::basic_string_view<char>)' being compiled
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1079): note: see reference to class template instantiation 'fmt::v8::detail::value<Context>' being compiled
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1835): note: see reference to class template instantiation 'fmt::v8::detail::arg_data<fmt::v8::detail::value<Context>,char,0,0>' being compiled
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/format.h(2473): note: see reference to class template instantiation 'fmt::v8::format_arg_store<fmt::v8::format_context>' being compiled
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/xchar.h(211): note: see reference to function template instantiation 'std::system_error fmt::v8::system_error<>(int,fmt::v8::basic_format_string<char>)' being compiled
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1243): error C4582: 'fmt::v8::detail::value<Context>::no_value': constructor is not implicitly called
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1243): note: while compiling class template member function 'fmt::v8::detail::value<Context>::value(const char *)'
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1731): note: see reference to function template instantiation 'fmt::v8::detail::value<Context>::value(const char *)' being compiled
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1232): error C4582: 'fmt::v8::detail::value<Context>::no_value': constructor is not implicitly called
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1232): note: while compiling class template member function 'fmt::v8::detail::value<Context>::value(int)'
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1731): note: see reference to function template instantiation 'fmt::v8::detail::value<Context>::value(int)' being compiled
            with
            [
                Context=fmt::v8::format_context
            ]
    [70/79] RiderGameControl.cpp
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1247): error C4582: 'fmt::v8::detail::value<Context>::no_value': constructor is not implicitly called
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1247): note: while compiling class template member function 'fmt::v8::detail::value<Context>::value(fmt::v8::basic_string_view<char>)'
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1731): note: see reference to function template instantiation 'fmt::v8::detail::value<Context>::value(fmt::v8::basic_string_view<char>)' being compiled
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1079): note: see reference to class template instantiation 'fmt::v8::detail::value<Context>' being compiled
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1835): note: see reference to class template instantiation 'fmt::v8::detail::arg_data<fmt::v8::detail::value<Context>,char,0,0>' being compiled
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/format.h(2473): note: see reference to class template instantiation 'fmt::v8::format_arg_store<fmt::v8::format_context>' being compiled
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/xchar.h(211): note: see reference to function template instantiation 'std::system_error fmt::v8::system_error<>(int,fmt::v8::basic_format_string<char>)' being compiled
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1243): error C4582: 'fmt::v8::detail::value<Context>::no_value': constructor is not implicitly called
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1243): note: while compiling class template member function 'fmt::v8::detail::value<Context>::value(const char *)'
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1731): note: see reference to function template instantiation 'fmt::v8::detail::value<Context>::value(const char *)' being compiled
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1232): error C4582: 'fmt::v8::detail::value<Context>::no_value': constructor is not implicitly called
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1232): note: while compiling class template member function 'fmt::v8::detail::value<Context>::value(int)'
            with
            [
                Context=fmt::v8::format_context
            ]
    C:\Users\Kevin\AppData\Local\Temp\UnrealLink\Wytofar\HostProject\Plugins\RiderLink\Source\RD\thirdparty\spdlog\include\spdlog/fmt/bundled/core.h(1731): note: see reference to function template instantiation 'fmt::v8::detail::value<Context>::value(int)' being compiled
            with
            [
                Context=fmt::v8::format_context
            ]
Took 72.2852975s to run UnrealBuildTool.exe, ExitCode=6
UnrealBuildTool failed. See log for more details. (C:\Users\Kevin\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.26\UBT-UE4Editor-Win64-Development.txt)
AutomationTool exiting with ExitCode=6 (6)
BUILD FAILED
Failed to build RiderLink plugin
Failed to build RiderLink plugin
```

I'm using a fresh Rider installation: `Build #RD-222.2680.9, built on May 30, 2022`

I also tried to extract RiderLink in Game and Engine, but it doesn't work either, same errors.

**Comment by dcx515253** [comment]
I got the same error after I upgraded Rider to 2022.2EAP2, my engine version is also 4.26

**Comment by dcx515253** [comment]
https://github.com/JetBrains/UnrealLink/commit/dccdc8aa08315531b7690812aa8a9fa02efba80b
Maybe it's because of this change

**Comment by oktomus** [comment]
I'm not sure, this cange is suppose to disable warnings

**Comment by helghast** [comment]
Same error after upgraded Rider to 2022.2EAP2
UE4.27.2

**Comment by oktomus** [comment]
I switched back to  `Rider 2022.1.1 Build #RD-221.5591.20, built on April 28, 2022` and it works 👌

**Comment by ArtemiyAAA** [comment]
Fixed since Rider 2022.2 EAP4
