### ISSUE TITLE
Rider Link don't compile on UE 5.3 Preview1

### ISSUE THREAD

**Issue by oahzuw** [JetBrains/UnrealLink#266]
RiderGameControl.cpp(296): error C4855: implicit capture of 'this' via '[=]' is deprecated in '/std:c++20'

**Comment by DecoyRS** [comment]
This one is already fixed and will be available in the next build

**Comment by julia-maliauka** [comment]
Hello! I am still seeing this error. How can I get the latest version of RiderLink/UnrealLink? It's bundled with Rider now, so I'm not sure how to ask it to update to the fixed version. I tried updating Rider & Toolbox to the latest versions. Any help is appreciated. Thank you!
